import './globals.css'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'

const font = Roboto({ subsets: ['latin'], weight: ['400', '700'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${font.className} text-base`}>{children}</body>
    </html>
  )
}
